name: CD

on:
  push:
    branches:
        - main
  pull_request:
    branches:
    - main

env:
  DEPLOY_KEY_PRIV: ${{ secrets.DEPLOY_KEY_PRIV }}
  EC2_DNS: ${{ secrets.EC2_DNS }}

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY_PRIV }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<EOT
          Host app_api
            HostName 54.211.223.58
            User ubuntu
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          EOT
      - name: Wait for backend folder
        run: |
         ssh app_api 'mkdir backend'
      # - name: Pull repo changes
      #   run: |
      #     ssh app_api 'cd backend && git fetch && git checkout main && git pull origin main'