name: CD

on:
  push:
    branches:
        - main
  pull_request:
    branches:
    - main

env:
  DEPLOY_KEY_PRIV: ${{ secrets.DEPLOY_KEY_PRIV }}
  EC2_DNS: ${{ secrets.EC2_DNS }}

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY_PRIV" | base64 --decode > ~/.ssh/deploy_key
          chmod 400 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<EOT
          Host app_api
            HostName $EC2_DNS
            User ubuntu
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          EOT
      - name: Wait for backend folder
        run: |
         ssh app_api 'until [ -d backend/ ]; do echo "Directory backend/ does not exist yet..."; sleep 5; done; echo "Directory backend/ found."'
      - name: Pull repo changes
        run: |
          ssh app_api 'cd backend && git fetch && git checkout main && git pull origin main'