name: CD

on:
  push:
    branches:
        - main
  pull_request:
    branches:
    - main

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY_PRIV" > ~/.ssh/deploy_key
          chmod 400 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<EOT
          Host app_api
            HostName $EC2_DNS
            User ubuntu
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          EOT

        env:
          DEPLOY_KEY_PRIV: ${{ secrets.DEPLOY_KEY_PRIV }}
          EC2_DNS: ${{ secrets.EC2_DNS }}

      - name: Wait for backend folder
        run: |
         ssh app_api 'mkdir backend'
      # - name: Pull repo changes
      #   run: |
      #     ssh app_api 'cd backend && git fetch && git checkout main && git pull origin main'